### ISSUE TITLE
Drop off or request label support

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#87]
Ability to reconcile orders that were dropped off or sent to bg by requesting a label.  We don't want to upload these trackings to portals as we are sending them home.  But would like to be able to match these up with a PO/tracking in bg portal.  Would also be extremly helpful if script could create a row/send an email when it detects a PO that has no matching tracking

**Comment by gbrodman** [comment]
OK so we 'd need to add a few things
1. Reading in PO numbers + receipt IDs from the sheet
2. Protecting that column to give a warning to the user
3. Reading in receipt IDs from, e.g. MYS and matching costs with those (maybe having maps of receipt_id -> cost and tracking_number -> receipt_id rather than the current tracking_number -> cost

1 and 3 will take some work, especially since they're kinda refactoring the architecture a bit
e.g. all the user-editable fields for now are only read by the scripts -- there's no field that is written to by both the user and the uatomation

**Comment by gbrodman** [comment]
note: in melul sites, tracking numbers can be a comma-separated list so make sure that we track all of those

**Comment by gbrodman** [comment]
> note: in melul sites, tracking numbers can be a comma-separated list so make sure that we track all of those

this is done, as is step 1 above

**Comment by gbrodman** [comment]
step 2 is done

**Comment by gbrodman** [comment]
step 1 is done, you can now manually edit

we still won't combine home / DE rows if they're tracked in the same PO, but I don't think that should be an issue. 

We also don't have a great way of verifying that a PO is unique -- we might match a USA PO payout # with a MYS receipt ID if they're the same...this really shouldn't happen but you never know

**Comment by gbrodman** [comment]
should be good to go with that last comment -- manually adding POs to ship-to-home orders is the way to do this
